graph TD
  a[string] --> b[string]
  a --> c[string]
  b --> z1[0]
  b --> d[string]
  b --> o1[1]
  d --> z2[0]
  d --> e[Empty]
  d --> o2[1]
  c --> o3[1]
  c --> f[string]
  c --> z3[0]
  f --> o4[1]
  f --> g[Empty]
  f --> z4[0]
