graph LR
  A["A: Start"]
  C["C: Accept"]
  F["F: Accept"]
  A -->|.| B
  B --> |"[0-9]"| C
  C --> |"[0-9]"| C
  C --> |E| D
  D --> |+,-| E
  D --> |"[0-9]"| F
  E --> |"[0-9]"| F
  F --> |"[0-9]"| F
