graph LR
  A["A: Start"]
  C["C: Accept"]
  F["F: Accept"]
  A --> |.| B
  A --> |"[0-9]"| G
  B --> |"[0-9]"| C
  C --> |"[0-9]"| C
  C --> |E| D
  D --> |+,-| E
  D --> |"[0-9]"| F

  E --> |"[0-9]"| F
  F --> |"[0-9]"| F

  G --> |"[0-9]"| G
  G --> |E| D
  G --> |.| C

  A --> |+,-,E| R
  B --> |+,-,E,.| R
  C --> |+,-,.| R
  D --> |E,.| R
  E --> |+,-,E,.| R
  F --> |+,-,E,.| R
  G --> |+,-| R
  R --> |"[0-9],+,-,E,."| R
