graph TB
  while-loop --> start-label
  while-loop --> condition
  while-loop --> jf[jump-false to end]
  while-loop --> statement-list
  while-loop --> j[jump to start]
  while-loop --> el[end-label]
